server:
 servlet:
    context-path: /controlador-sondas/api
    
springdoc:
  swagger-ui:
    path: /public/swagger
    
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: foo
    password: bar
    driverClassName: org.postgresql.Driver
